# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/brentrubell/Desktop/github_brentru/lab-mouse-eyedropper/app/posiapp/gui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(577, 642)
        MainWindow.setAnimated(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox_xaxis = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_xaxis.setGeometry(QtCore.QRect(10, 10, 151, 101))
        self.groupBox_xaxis.setObjectName("groupBox_xaxis")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_xaxis)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 131, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_x_left = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_x_left.setObjectName("btn_x_left")
        self.verticalLayout.addWidget(self.btn_x_left)
        self.btn_x_right = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_x_right.setObjectName("btn_x_right")
        self.verticalLayout.addWidget(self.btn_x_right)
        self.groupBox_syringe = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_syringe.setGeometry(QtCore.QRect(160, 110, 171, 101))
        self.groupBox_syringe.setObjectName("groupBox_syringe")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_syringe)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 151, 66))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_syr_in = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.btn_syr_in.setObjectName("btn_syr_in")
        self.verticalLayout_7.addWidget(self.btn_syr_in)
        self.btn_syr_out = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.btn_syr_out.setObjectName("btn_syr_out")
        self.verticalLayout_7.addWidget(self.btn_syr_out)
        self.groupBox_yaxis = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_yaxis.setEnabled(True)
        self.groupBox_yaxis.setGeometry(QtCore.QRect(10, 110, 151, 101))
        self.groupBox_yaxis.setObjectName("groupBox_yaxis")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_yaxis)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 131, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_y_up = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_y_up.setObjectName("btn_y_up")
        self.verticalLayout_3.addWidget(self.btn_y_up)
        self.btn_y_down = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_y_down.setObjectName("btn_y_down")
        self.verticalLayout_3.addWidget(self.btn_y_down)
        self.btn_quit = QtWidgets.QPushButton(self.centralWidget)
        self.btn_quit.setGeometry(QtCore.QRect(170, 520, 71, 61))
        self.btn_quit.setObjectName("btn_quit")
        self.groupBox_platform = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_platform.setGeometry(QtCore.QRect(160, 10, 171, 91))
        self.groupBox_platform.setObjectName("groupBox_platform")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_platform)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 151, 66))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_platform_right = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.btn_platform_right.setObjectName("btn_platform_right")
        self.verticalLayout_8.addWidget(self.btn_platform_right)
        self.btn_platform_left = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.btn_platform_left.setObjectName("btn_platform_left")
        self.verticalLayout_8.addWidget(self.btn_platform_left)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 210, 161, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.label_7.setObjectName("label_7")
        self.lbl_power = QtWidgets.QLabel(self.groupBox_7)
        self.lbl_power.setGeometry(QtCore.QRect(60, 30, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_power.setFont(font)
        self.lbl_power.setObjectName("lbl_power")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 61, 21))
        self.label_9.setObjectName("label_9")
        self.lbl_serial_status = QtWidgets.QLabel(self.groupBox_7)
        self.lbl_serial_status.setGeometry(QtCore.QRect(60, 60, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_serial_status.setFont(font)
        self.lbl_serial_status.setObjectName("lbl_serial_status")
        self.groupBox_presets = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_presets.setGeometry(QtCore.QRect(200, 210, 111, 101))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_presets.setFont(font)
        self.groupBox_presets.setObjectName("groupBox_presets")
        self.btn_ps1 = QtWidgets.QPushButton(self.groupBox_presets)
        self.btn_ps1.setGeometry(QtCore.QRect(10, 30, 41, 21))
        self.btn_ps1.setObjectName("btn_ps1")
        self.btn_ps1_set = QtWidgets.QPushButton(self.groupBox_presets)
        self.btn_ps1_set.setGeometry(QtCore.QRect(60, 30, 31, 21))
        self.btn_ps1_set.setObjectName("btn_ps1_set")
        self.btn_ps2 = QtWidgets.QPushButton(self.groupBox_presets)
        self.btn_ps2.setGeometry(QtCore.QRect(10, 50, 41, 21))
        self.btn_ps2.setObjectName("btn_ps2")
        self.btn_ps3 = QtWidgets.QPushButton(self.groupBox_presets)
        self.btn_ps3.setGeometry(QtCore.QRect(10, 70, 41, 21))
        self.btn_ps3.setObjectName("btn_ps3")
        self.btn_ps2_set = QtWidgets.QPushButton(self.groupBox_presets)
        self.btn_ps2_set.setGeometry(QtCore.QRect(60, 50, 31, 21))
        self.btn_ps2_set.setObjectName("btn_ps2_set")
        self.btn_ps3_set = QtWidgets.QPushButton(self.groupBox_presets)
        self.btn_ps3_set.setGeometry(QtCore.QRect(60, 70, 31, 21))
        self.btn_ps3_set.setObjectName("btn_ps3_set")
        self.groupBox_camera = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_camera.setGeometry(QtCore.QRect(350, 0, 211, 291))
        self.groupBox_camera.setObjectName("groupBox_camera")
        self.btn_cam1_start = QtWidgets.QPushButton(self.groupBox_camera)
        self.btn_cam1_start.setGeometry(QtCore.QRect(10, 240, 91, 31))
        self.btn_cam1_start.setObjectName("btn_cam1_start")
        self.btn_cam1_pause = QtWidgets.QPushButton(self.groupBox_camera)
        self.btn_cam1_pause.setGeometry(QtCore.QRect(110, 240, 91, 31))
        self.btn_cam1_pause.setObjectName("btn_cam1_pause")
        self.btn_cam1_screenshot = QtWidgets.QPushButton(self.groupBox_camera)
        self.btn_cam1_screenshot.setGeometry(QtCore.QRect(60, 260, 91, 31))
        self.btn_cam1_screenshot.setObjectName("btn_cam1_screenshot")
        self.lbl_cam1 = QtWidgets.QLabel(self.groupBox_camera)
        self.lbl_cam1.setGeometry(QtCore.QRect(10, 30, 191, 211))
        self.lbl_cam1.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_cam1.setText("")
        self.lbl_cam1.setObjectName("lbl_cam1")
        self.lbl_cam_1_activity = QtWidgets.QLabel(self.groupBox_camera)
        self.lbl_cam_1_activity.setGeometry(QtCore.QRect(180, -10, 81, 41))
        self.lbl_cam_1_activity.setObjectName("lbl_cam_1_activity")
        self.btn_estop = QtWidgets.QPushButton(self.centralWidget)
        self.btn_estop.setGeometry(QtCore.QRect(10, 490, 161, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 0, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        self.btn_estop.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_estop.setFont(font)
        self.btn_estop.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_estop.setCheckable(False)
        self.btn_estop.setObjectName("btn_estop")
        self.groupBox_camera_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_camera_2.setGeometry(QtCore.QRect(350, 290, 211, 291))
        self.groupBox_camera_2.setObjectName("groupBox_camera_2")
        self.btn_cam2_start = QtWidgets.QPushButton(self.groupBox_camera_2)
        self.btn_cam2_start.setGeometry(QtCore.QRect(10, 240, 91, 31))
        self.btn_cam2_start.setObjectName("btn_cam2_start")
        self.btn_cam2_pause = QtWidgets.QPushButton(self.groupBox_camera_2)
        self.btn_cam2_pause.setGeometry(QtCore.QRect(110, 240, 91, 31))
        self.btn_cam2_pause.setObjectName("btn_cam2_pause")
        self.btn_cam2_screenshot = QtWidgets.QPushButton(self.groupBox_camera_2)
        self.btn_cam2_screenshot.setGeometry(QtCore.QRect(60, 260, 91, 31))
        self.btn_cam2_screenshot.setObjectName("btn_cam2_screenshot")
        self.lbl_cam2 = QtWidgets.QLabel(self.groupBox_camera_2)
        self.lbl_cam2.setGeometry(QtCore.QRect(10, 30, 191, 211))
        self.lbl_cam2.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_cam2.setText("")
        self.lbl_cam2.setObjectName("lbl_cam2")
        self.lbl_cam2_activity = QtWidgets.QLabel(self.groupBox_camera_2)
        self.lbl_cam2_activity.setGeometry(QtCore.QRect(180, -10, 81, 41))
        self.lbl_cam2_activity.setObjectName("lbl_cam2_activity")
        self.groupBox_comms = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_comms.setEnabled(True)
        self.groupBox_comms.setGeometry(QtCore.QRect(10, 310, 161, 161))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_comms.setFont(font)
        self.groupBox_comms.setObjectName("groupBox_comms")
        self.btn_power = QtWidgets.QPushButton(self.groupBox_comms)
        self.btn_power.setGeometry(QtCore.QRect(10, 30, 141, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_power.setFont(font)
        self.btn_power.setObjectName("btn_power")
        self.btn_disable_steppers = QtWidgets.QPushButton(self.groupBox_comms)
        self.btn_disable_steppers.setGeometry(QtCore.QRect(10, 70, 141, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_disable_steppers.setFont(font)
        self.btn_disable_steppers.setObjectName("btn_disable_steppers")
        self.btn_disconnect = QtWidgets.QPushButton(self.groupBox_comms)
        self.btn_disconnect.setGeometry(QtCore.QRect(10, 110, 141, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_disconnect.setFont(font)
        self.btn_disconnect.setObjectName("btn_disconnect")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(170, 310, 171, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 61, 31))
        self.label_8.setObjectName("label_8")
        self.comboBox_ports = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_ports.setGeometry(QtCore.QRect(40, 20, 121, 31))
        self.comboBox_ports.setObjectName("comboBox_ports")
        self.btn_refreshPorts = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_refreshPorts.setGeometry(QtCore.QRect(30, 110, 113, 32))
        self.btn_refreshPorts.setObjectName("btn_refreshPorts")
        self.btn_connectSerial = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_connectSerial.setGeometry(QtCore.QRect(20, 80, 131, 32))
        self.btn_connectSerial.setObjectName("btn_connectSerial")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 577, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuPositioner = QtWidgets.QMenu(self.menuBar)
        self.menuPositioner.setObjectName("menuPositioner")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuPositioner.addSeparator()
        self.menuPositioner.addAction(self.actionFile)
        self.menuPositioner.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuPositioner.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Positioner Panel"))
        self.groupBox_xaxis.setTitle(_translate("MainWindow", "X-Axis"))
        self.btn_x_left.setText(_translate("MainWindow", "Left"))
        self.btn_x_right.setText(_translate("MainWindow", "Right"))
        self.groupBox_syringe.setTitle(_translate("MainWindow", "Syringe"))
        self.btn_syr_in.setText(_translate("MainWindow", "Towards Mouse"))
        self.btn_syr_out.setText(_translate("MainWindow", "Away from Mouse"))
        self.groupBox_yaxis.setTitle(_translate("MainWindow", "Y-Axis"))
        self.btn_y_up.setText(_translate("MainWindow", "Up"))
        self.btn_y_down.setText(_translate("MainWindow", "Down"))
        self.btn_quit.setText(_translate("MainWindow", "Quit"))
        self.groupBox_platform.setTitle(_translate("MainWindow", "Platform "))
        self.btn_platform_right.setText(_translate("MainWindow", "Rotate Right"))
        self.btn_platform_left.setText(_translate("MainWindow", "Rotate Left"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Information"))
        self.label_7.setText(_translate("MainWindow", "Power:"))
        self.lbl_power.setText(_translate("MainWindow", "Off"))
        self.label_9.setText(_translate("MainWindow", "Serial:"))
        self.lbl_serial_status.setText(_translate("MainWindow", "Disconnected"))
        self.groupBox_presets.setTitle(_translate("MainWindow", "Motion Presets"))
        self.btn_ps1.setText(_translate("MainWindow", "PS1"))
        self.btn_ps1_set.setText(_translate("MainWindow", "set"))
        self.btn_ps2.setText(_translate("MainWindow", "PS2"))
        self.btn_ps3.setText(_translate("MainWindow", "PS3"))
        self.btn_ps2_set.setText(_translate("MainWindow", "set"))
        self.btn_ps3_set.setText(_translate("MainWindow", "set"))
        self.groupBox_camera.setTitle(_translate("MainWindow", "Video Feed 1"))
        self.btn_cam1_start.setText(_translate("MainWindow", "start"))
        self.btn_cam1_pause.setText(_translate("MainWindow", "pause"))
        self.btn_cam1_screenshot.setText(_translate("MainWindow", "screenshot"))
        self.lbl_cam_1_activity.setText(_translate("MainWindow", "Idle"))
        self.btn_estop.setText(_translate("MainWindow", "EMERGENCY STOP"))
        self.groupBox_camera_2.setTitle(_translate("MainWindow", "Video Feed 2"))
        self.btn_cam2_start.setText(_translate("MainWindow", "start"))
        self.btn_cam2_pause.setText(_translate("MainWindow", "pause"))
        self.btn_cam2_screenshot.setText(_translate("MainWindow", "screenshot"))
        self.lbl_cam2_activity.setText(_translate("MainWindow", "Idle"))
        self.groupBox_comms.setTitle(_translate("MainWindow", "Power and Comms."))
        self.btn_power.setText(_translate("MainWindow", "Power On"))
        self.btn_disable_steppers.setText(_translate("MainWindow", "Disable Motors"))
        self.btn_disconnect.setText(_translate("MainWindow", "Disconnect Serial"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Settings"))
        self.label_8.setText(_translate("MainWindow", "Port:"))
        self.btn_refreshPorts.setText(_translate("MainWindow", "Refresh Ports"))
        self.btn_connectSerial.setText(_translate("MainWindow", "Connect Machine"))
        self.menuPositioner.setTitle(_translate("MainWindow", "Positioner"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

